In [1]:
import pandas as pd
import matplotlib as plt

In [5]:
data = pd.DataFrame([
    [2.900000095, 4],
    [6.699999809, 7.400000095],
    [4.900000095, 5],
    [7.900000095, 7.199999809],
    [9.800000191, 7.900000095],
    [6.900000095, 6.099999905],
    [6.099999905, 6],
    [6.199999809, 5.800000191],
    [6, 5.199999809],
    [5.099999905, 4.199999809],
    [4.699999809, 4],
    [4.400000095, 4.400000095],
    [5.800000191, 5.199999809]
],columns=["grad","gpa"])

data

    grad  gpa
0    2.9  4.0
1    6.7  7.4
2    4.9  5.0
3    7.9  7.2
4    9.8  7.9
5    6.9  6.1
6    6.1  6.0
7    6.2  5.8
8    6.0  5.2
9    5.1  4.2
10   4.7  4.0
11   4.4  4.4
12   5.8  5.2

In [6]:
#step of gradin disand 
#1 intial paramter q0 ,q1 and alpa
#2 clclate the y predict 
#3 compute eror y -yhpridct 
#4 cluclate gradien
#5 update the valuabel

In [9]:
# step 1
q0 = 0
q1 = 0
alph = 0.02

In [ ]:
# step 2
def predict(vectorx,q0,q1):
    return vectorx*q1+q0

#step 3 
def vector_error(y, y_predict):
    error = y-y_predict
    return error**2 / len(y)
def mean_squared_error(y, y_predict):
    error = y-y_predict
    return sum(error**2) / len(y)